In [2]:
import numpy as np

arr=np.arange(50,101)
arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [17]:
arr1=np.ones((3,3))
print(arr1)
arr1_pad=np.pad(arr1,pad_width=1,mode='constant',constant_values=0)
arr1_pad

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
l1=[1,2,3,4,5,6,7,8]
l1
tup1=(8,4,6,1,2,3)
arr2=np.array(tup1)

arr2 =arr2.reshape(2,3)
arr2

array([[8, 4, 6],
       [1, 2, 3]])

In [36]:
frnht_arr=np.array([0.,   12.,   45.21, 34.,   99.91])
frnht_arr
(frnht_arr-32)*5/9

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

In [54]:

print("Size of the array:",arr.size)
print("Length of one array element in bytes",arr.itemsize)
print("Total bytes consumed by the elements of the array: ",arr.itemsize*arr.size)



Size of the array: 51
Length of one array element in bytes 4
Total bytes consumed by the elements of the array:  204


In [56]:
#Change the dimension of an array
arr3=np.array([10,10,20,30,10,30,20,40,50])
arr3.reshape(3,3)



array([[10, 10, 20],
       [30, 10, 30],
       [20, 40, 50]])

In [94]:
#Get the unique elements of an array
print("Original array with duplicate elements")
print(arr3)
arr3=np.unique(arr3)
print("new array with unique elements")
print(arr3)
arr_2d_1=np.array([[1,1],[2,3]])
print("Two Dimension array ")
print(arr_2d_1)
print("new array with unique elements")
arr_2d_1=np.unique(arr_2d_1)
print(arr_2d_1)

Original array with duplicate elements
[10 20 30 40 50]
new array with unique elements
[10 20 30 40 50]
Two Dimension array 
[[1 1]
 [2 3]]
new array with unique elements
[1 2 3]


In [61]:
#Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive¶
np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [67]:
#Convert 1-D arrays as columns into a 2-D array
arr_1=np.array([100,200,300,400])
arr_2=np.array([1000,3000,5,800])
print(arr_1)
print(arr_2)
arr_2d=np.stack((arr_1,arr_2),axis=1)
arr_2d
#arr_2d=arr_2d.

[100 200 300 400]
[1000 3000    5  800]


array([[ 100, 1000],
       [ 200, 3000],
       [ 300,    5],
       [ 400,  800]])

In [96]:
#Create a 5x5 matrix with row values ranging from 0 to 4
arr_5=np.zeros((5,5))
print("Original 5*5 Metrics")
print(arr_5)
print("row values ranging from 0 to 4")
arr_5+=np.arange(5)
print(arr_5)


Original 5*5 Metrics
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
row values ranging from 0 to 4
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [86]:
#Sum of all the multiples of 3 or 5 below 100
arr5=np.arange(1,100)
list_arr=[]
sumarr=0
for i in arr5:
    if(i%3==0 or i%5==0):
        #print(i)
        list_arr.append(i)
        sumarr=sumarr+i
print(list_arr)   
print(sumarr)

            
    


[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]
2318


In [104]:
#Combine a one and a two dimensional array together and display their elements
#np.nditor()
arr_1d=np.array([99,88,77])
print(arr_1d)
arr_2d=np.array([[1,2,3],[8,9,10]])
print(arr_2d)
#arr_con=np.concatenate((arr_1d,arr_2d),axis=0)

for a,b in np.nditer([arr_1d,arr_2d]):
    print("%d:%d"%(a,b))
    


[99 88 77]
[[ 1  2  3]
 [ 8  9 10]]
99:1
88:2
77:3
99:8
88:9
77:10


In [115]:
#Write a NumPy program to replace all elements of NumPy array that are greater than specified array
arr6=np.linspace(0.1,1.0,9)
arr6=arr6.reshape((3,3))
print("Original Array")
print(arr6)
#arr6[arr6>=0.5]=0.5
print("After replaced with .5 which are greater than .5")
#print(arr6)
np.where(arr6>0.5,0.5,arr6)


Original Array
[[0.1    0.2125 0.325 ]
 [0.4375 0.55   0.6625]
 [0.775  0.8875 1.    ]]
After replaced with .5 which are greater than .5


array([[0.1   , 0.2125, 0.325 ],
       [0.4375, 0.5   , 0.5   ],
       [0.5   , 0.5   , 0.5   ]])

In [131]:
#Add a new row to an empty numpy array
emp_arr=np.empty((0,3),int)
print("Empty Array")
print(emp_arr)
emp_err=np.append(emp_arr,np.array([[10,20,20]]),axis=0)
#print(add_err)
emp_err=np.append(emp_arr,np.array([[90,80,70]]),axis=0)
print(add_arr)


Empty Array
[]
[[90 80 70]]


In [3]:
#Write a NumPy program to join a sequence of arrays along a new axis
x=np.array([1,2,3])
y=np.array([4,5,6])
print("Original Array")
print(x)
print(y)

Original Array
[1 2 3]
[4 5 6]


In [5]:
print("New Array along a new axis")
print(np.vstack((x,y)))

[[1 2 3]
 [4 5 6]]


In [9]:
a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])
print("Original Array")
print(a)
print(b)
print("New Array along a new axis")
print(np.vstack((a,b)))


Original Array
[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
New Array along a new axis
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
